# Generated by Django 4.0 on 2023-12-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientExplabs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, null=True)),
                ('client_type', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_explabs',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pkg_name', models.TextField(blank=True, null=True)),
                ('cost_per_credits', models.TextField(blank=True, null=True)),
                ('minimum_credits', models.TextField(blank=True, null=True)),
                ('reorder_level', models.TextField(blank=True, db_column='reorder-level', null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_saas', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.client')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='ClientPkg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_type', models.TextField(blank=True, db_column='billing-type', null=True)),
                ('credits', models.BigIntegerField(blank=True, null=True)),
                ('balance', models.BigIntegerField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('compid', models.ForeignKey(blank=True, db_column='compid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.clientexplabs')),
                ('pkg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.subscription')),
            ],
            options={
                'db_table': 'client_pkg',
            },
        ),
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('copanyid', models.ForeignKey(blank=True, db_column='copanyid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.clientexplabs')),
            ],
            options={
                'db_table': 'client_location',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rep_name', models.TextField(blank=True, null=True)),
                ('cell_no', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('taxid', models.TextField(blank=True, null=True)),
                ('clientid', models.ForeignKey(blank=True, db_column='clientid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.client')),
            ],
            options={
                'db_table': 'client_contact',
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('accounting_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('ort_session_time', models.FloatField(blank=True, null=True)),
                ('matting_time', models.FloatField(blank=True, null=True)),
                ('main_operation_time', models.FloatField(blank=True, null=True)),
                ('image_download_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.location')),
            ],
            options={
                'db_table': 'accounting',
            },
        ),
    ]
