# Generated by Django 4.0 on 2023-12-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserloginExp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('lastlogin', models.DateField(blank=True, null=True)),
                ('ispwdchange', models.BooleanField(blank=True, null=True)),
                ('isadmin', models.BooleanField(blank=True, db_column='isAdmin', null=True)),
                ('client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imagex.clientcontact')),
            ],
            options={
                'db_table': 'userlogin_exp',
            },
        ),
    ]
