# Generated by Django 4.0 on 2023-12-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagex', '0002_userloginexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginexp',
            name='isadmin',
        ),
    ]
